### ISSUE TITLE
Bucket Name

### ISSUE THREAD

**Issue by cfis** [ceph/ceph-cosi#31]
When I create a bucket claim, the bucket that is created has a long random name in ceph. That isn't helpful since we have code that is hard-coded against specific bucket names.

Is there anyway to control the final bucket name?

**Comment by cfis** [comment]
Yes, ok. Could it be rook doing it?

**Comment by thotz** [comment]
> Yes, ok. Could it be rook doing it?

Rook only sets up ceph cosi driver. Does not interfere with COSI CRDs like bucketclaim, bucket access etc. I actually forgot the steps, but I am guessing u can directly create `Bucket` resource without BucketClaim for brownfield(already existing buckets). I am not sure whether it covers this use-case as well
